#! /bin/sh
##--Monitors--##
bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10
###---Global Settings---###
bspc config automatic_scheme spiral
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#6a6c6e"
bspc config active_border_color	"#6a6c6e"
bspc config focused_border_color "#e8e9eb"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 3
bspc config window_gap 10

###---Rules---###
bspc rule -a mpv state=fullscreen # makes MPV stay in fullscreen
bspc rule -a Soffice state=tiled # makes libreoffice not crash
bspc rule -a Zathura state=tiled # why zathura isn't tiled to begin with, i have no idea
bspc rule -a Emacs state=tiled
bspc rule -a qjackctl state=floating # looks ugly as shit tiled

##--Autostart Applications--##
#killall "nm-applet"
#nm-applet &
#killall "sxhkd"
#sxhkd &
##mate-panel &
~/.config/polybar/launch.sh --colorblocks &
##mate-power-manager &
#killall "picom"
#picom &
#redshift -l 42.43933:-123.33067 &
#killall "pnmixer"
#pnmixer &
#setxkbmap -option caps:escape &
#killall syncthing
#syncthing --no-browser &
#wmname compiz & # pretends to be another window manager so certain java applications will actually run in bspwm
#wal -R -n &
#~/.screenlayout/default.sh &
#nitrogen --restore &
