#! /bin/sh
##--Monitors--##
bspc monitor LVDS-1 -d I II III IV V VI VII VIII IX X
###---Global Settings---###
bspc config automatic_scheme spiral
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 0
bspc config window_gap 7

##--Autostart Applications--##
killall "nm-applet"
nm-applet &
killall "sxhkd"
sxhkd &
tint2 -c ~/.config/tint2/tint2rc &
wal -R &
killall "compton"
compton --config ~/.config/compton/compton.conf &
redshift -l 42.43933:-123.33067 &
killall "pnmixer"
pnmixer &
syncthing --no-browser &
setxkbmap -option caps:escape &

###---Rules---###
bspc rule -a mpv state=fullscreen # makes MPV stay in fullscreen
bspc rule -a Soffice state=tiled # makes libreoffice not crash
bspc rule -a Zathura state=tiled # why zathura isn't tiled to begin with, i have no idea
bspc rule -a Emacs state=tiled
