includePaths:
    -   /home/gayms/.local/share/SuperCollider/downloaded-quarks/Vowel
    -   /home/gayms/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples
    -   /home/gayms/.local/share/SuperCollider/downloaded-quarks/SuperDirt
excludePaths:
    []
postInlineWarnings: false
excludeDefaultPaths: false